### ISSUE TITLE
Missing class qProduct

### ISSUE THREAD

**Issue by TomSeVeT** [elenamountz/spring-boot-rest-api-warehouse#1]
However thanks A LOT! Your project gave me opportunity to learn how to REST API ;D

**Comment by elenamountz** [comment]
Hey, thanks for your feedback. It does not seem to be an issue. 

**qProduct** is let's say an instance of **QProduct** class. QClasses, generally, will automatically be generated under the **/target/generated-sources** directory, when you build the project. It makes sense that you cannot use QClasses and their instances, if you don't build the project first.

Did you try to execute the maven goals described in readme file? You can run the goals using both terminal or your IDE.
